[package]
name = "pandoc_datalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cozo = "0.7.6"
itertools = "0.12.1"
pandoc_types = "0.6.0"
serde = "1.0.197"
serde_json = "1.0.114"
